/**
 * Environment file management:
 * - Copy .env files from source to destination
 * - Apply port offset transforms to .env files
 * - Write .env.superset with allocated ports
 */

import { existsSync, mkdirSync } from "fs";
import { join, dirname, relative } from "path";
import { Glob } from "bun";

/**
 * Find all .env* files in a directory (excluding .git and node_modules)
 */
async function findEnvFiles(dir: string): Promise<string[]> {
  const glob = new Glob("**/.env*");
  const files: string[] = [];

  for await (const file of glob.scan({
    cwd: dir,
    dot: true,
    absolute: false,
    followSymlinks: false,
  })) {
    if (file.includes(".git/") || file.includes("node_modules/")) continue;
    files.push(file);
  }

  return files;
}

/**
 * Copy .env files from source to destination, preserving directory structure.
 */
export async function copyEnvFiles(src: string, dst: string): Promise<number> {
  const files = await findEnvFiles(src);
  let count = 0;

  for (const relPath of files) {
    const srcFile = join(src, relPath);
    const dstFile = join(dst, relPath);
    const dstDir = dirname(dstFile);

    // Only copy if destination directory exists (don't create new service dirs)
    if (!existsSync(dstDir)) continue;

    const content = await Bun.file(srcFile).text();
    await Bun.write(dstFile, content);
    count++;
  }

  return count;
}

/**
 * Apply port offset to all .env* files in a directory.
 * Transforms:
 *   - KEY_WITH_PORT=NNNN  → KEY_WITH_PORT=NNNN+offset
 *   - localhost:NNNN      → localhost:NNNN+offset
 *   - 127.0.0.1:NNNN      → 127.0.0.1:NNNN+offset
 */
export async function applyPortOffset(dir: string, offset: number): Promise<number> {
  if (offset === 0) return 0;

  const files = await findEnvFiles(dir);
  let modified = 0;

  for (const relPath of files) {
    const filePath = join(dir, relPath);
    const content = await Bun.file(filePath).text();
    let changed = false;
    const lines = content.split("\n");

    const newLines = lines.map((line) => {
      // Skip comments and empty
      if (/^\s*#/.test(line) || line.trim() === "") return line;

      let newLine = line;

      // Match: VAR_WITH_PORT=NNNN (key contains PORT, value is a number)
      const portVarMatch = newLine.match(/^([A-Za-z_]*PORT[A-Za-z_]*)=(\d+)$/);
      if (portVarMatch) {
        const key = portVarMatch[1];
        const port = parseInt(portVarMatch[2], 10);
        newLine = `${key}=${port + offset}`;
        changed = true;
      }

      // Match: localhost:NNNN or 127.0.0.1:NNNN in values
      const hostPortRegex = /(localhost|127\.0\.0\.1):(\d+)/g;
      let hostMatch;
      while ((hostMatch = hostPortRegex.exec(line)) !== null) {
        const host = hostMatch[1];
        const port = parseInt(hostMatch[2], 10);
        newLine = newLine.replace(`${host}:${port}`, `${host}:${port + offset}`);
        changed = true;
      }

      return newLine;
    });

    if (changed) {
      await Bun.write(filePath, newLines.join("\n"));
      modified++;
    }
  }

  return modified;
}

/**
 * Write .env.superset with allocated port values
 */
export async function writeEnvSuperset(
  dir: string,
  ports: Record<string, number>,
  offset: number
): Promise<void> {
  const lines = [
    "# Generated by wizrd-superset — do not edit manually",
    `PORT_OFFSET=${offset}`,
    "",
  ];

  for (const [name, port] of Object.entries(ports)) {
    const envVar = name.toUpperCase().replace(/[^A-Z0-9]/g, "_") + "_PORT";
    lines.push(`${envVar}=${port}`);
  }

  lines.push("");
  await Bun.write(join(dir, ".env.superset"), lines.join("\n"));
}
